[general]
import = [
  "themes/catppuccin-mocha.toml",
]

[terminal]
shell = "/bin/zsh"

[window]
padding = { x = 8, y = 8 }
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MonaspiceNe Nerd Font Mono", style = "Regular" }
size = 13

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }

